[project]
name = "sat0008-outlook-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pywin32>=308",
    "regex>=2024.11.6",
    "thefuzz>=0.22.1",
]
